name: Build Android
on:
  workflow_dispatch: # Permet de lancer le build manuellement

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Build locally
        run: eas build --platform android --profile production --local --non-interactive

      - name: 📂 Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: ./*.aab
